# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net
  
trigger:
- master

variables:
  solution: '**/*.sln'
  appname: 'CommodQuant'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  vmImageName: 'windows-2019'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
        - task: NuGetToolInstaller@0

        - task: NuGetCommand@2
          inputs:
            restoreSolution: '$(solution)'

        - script: dotnet restore

        - script: dotnet publish --configuration $(buildConfiguration) 

        - upload: src/Test/bin/$(buildConfiguration)/netcoreapp2.2/publish/* 
          artifact: Test

        - upload: src/Library/bin/Release/netcoreapp2.2/publish/* 
          artifact: Release
        
  - stage: Dev
    displayName: Dev stage
    dependsOn: Build
    condition: succeeded('Build')
    jobs:
    - deployment: Dev
      displayName: Dev
      environment: 'development'
      pool: 
        vmImage: $(vmImageName)
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: Test
            - script: dotnet vstest Test.dll
  - stage: Prod
    displayName: Prod stage
    dependsOn: Dev
    condition: succeeded('Dev')
    jobs:
    - deployment: Prod
      displayName: Prod
      environment: 'production'
      pool: 
        vmImage: $(vmImageName)
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: Release
            
 